server.port=8092
spring.config.name=masters
server.servlet.context-path=/masters
spring.application.name=masters
spring.datasource.url=jdbc:postgresql://localhost:5432/hims
spring.datasource.username=root
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update

spring.mvc.pathmatch.matching-strategy=ant_path_matcher
spring.main.allow-bean-definition-overriding=true
#spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
#spring.jpa.properties.hibernate.format_sql=true

#it start logging related to hikari
logging.level.com.zaxxer.hikari=DEBUG

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=5000
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=600000