server.port=8092
spring.config.name=masters
server.servlet.context-path=/masters
spring.application.name=masters
spring.datasource.url=jdbc:postgresql://localhost:5432/hims
#spring.datasource.username=root
#spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update


spring.datasource.username=postgres
spring.datasource.password=admin

spring.mvc.pathmatch.matching-strategy=ant_path_matcher
spring.main.allow-bean-definition-overriding=true
#spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
#spring.jpa.properties.hibernate.format_sql=true
spring.flyway.enabled=true
spring.flyway.locations=classpath:flyway_migration
spring.flyway.baseline-on-migrate=true
spring.flyway.clean-disabled=true
hims.function-self-heal.enabled=true
hims.function-self-heal.paths=masters/sqlscript
hims.function-self-heal.schema=public

#it start logging related to hikari
logging.level.com.zaxxer.hikari=DEBUG

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=5000
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=600000